---
image: python:3.7


stages:
  - package
  - deploy


package:
  stage: package
  before_script:
    - source .gitlab-ci.env
    - chmod a+x tools/set_version
    - tools/set_version
    - pip install --upgrade build
  script:
    - python -m build --no-isolation --outdir dist
  artifacts:
    paths:
      - dist
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9-\.]+)?$/'


deploy:
  stage: deploy
  before_script:
    - source .gitlab-ci.env
    - pip install --upgrade wheel twine
  script:
    - python -m twine upload --username __token__ --password ${PYPI_API_TOKEN} --non-interactive --disable-progress-bar --repository-url ${PYPI_REPOSITORY_URL} dist/*
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9-\.]+)?$/'
